services:
  onaylf_web:
    build: .
    container_name: onaylf_django
    restart: unless-stopped
    command: bash -c "./wait-for-postgres.sh onaylf_db && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8100"
    volumes:
      - static:/app/static
      - ./wait-for-postgres.sh:/app/wait-for-postgres.sh
    expose:
      - 8100
    env_file:
      - .env
    depends_on:
      onaylf_db:
        condition: service_healthy

  onaylf_db:
    image: postgres
    container_name: onaylf_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -U postgres -d template1 -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  onaylf_nginx:
    build: ./nginx
    container_name: onaylf_nginx
    restart: unless-stopped
    volumes:
      - static:/static/
    expose:
      - 8181
    depends_on:
      - onaylf_web

volumes:
  postgres_data:
  static:

networks:
  default:
    external: true
    name: nginxproxymanager_default