services:
  web:
    build: .
    container_name: onaylf_gunicorn
    restart: unless-stopped
    command: bash -c "./wait-for-postgres.sh db && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8100"
    volumes:
      - static:/app/static
      - ./wait-for-postgres.sh:/app/wait-for-postgres.sh
    expose:
      - 8100
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: postgres_onaylf
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 6

  nginx:
    build: ./nginx
    container_name: onaylf_nginx
    restart: unless-stopped
    volumes:
      - static:/static/
    expose:
      - 8181
    depends_on:
      - web

volumes:
  postgres_data:
  static:

networks:
  default:
    external: true
    name: nginxproxymanager_default